name: Load Testing
on: [push]
jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install k6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
      - name: Run k6
        run: k6 run load-testing/load_test.js --out json=reports/load/results.json || true
      - name: Parse results
        run: python load-testing/parse_load_test.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: reports/load/
